import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./Themeprovider";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Rustflix",
    description: "Generated by ...",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ClerkProvider>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <body
                        className={`${inter.className} relative min-h-screen max-w-full`}
                    >
                        <Nav />
                        <main className="pt-16">
                            {children}
                        </main>
                        <Footer />
                    </body>
                </ThemeProvider>
            </ClerkProvider>
        </html>
    );
}
